### PR TITLE
page: health and safety guidelines

### PR DESCRIPTION
**Pull request by basiima**
create a new page for health and safety guidelines

### CODE REVIEW

**Comment by Amanya-Brian** [comment]
Looks fine. Thanks

**Comment by HassanBahati** [comment]
i see there was a failing CI...so i would suspect the pr had some errors
@Amanya-Brian what could have been the deploy logs https://app.netlify.com/sites/pyconug/deploys/645f7cb3c0273e0007b5a639
image

**Comment by basiima** [comment]
I suspect breaking characters such quotation marks in the text that cause these errors. NextJS is sensitive to them

**Comment by basiima** [comment]
But if there's any other cause, please point them out

**Comment by HassanBahati** [comment]
have you tried accessing the page? 

locally it appears 
image


but what has been merged is 
image

**Comment by HassanBahati** [comment]
i suggest reverting the merge of the pull request so we fix the errors

**Comment by HassanBahati** [comment]
> But if there's any other cause, please point them out

@basiima the deploy logs have them all.... @Amanya-Brian could share a screenshot of the failing deploy logs

**Comment by Amanya-Brian** [comment]
image

It's a build error

**Comment by HassanBahati** [comment]
@basiima the change to make is  around there on `line 14`
image

**Comment by basiima** [comment]
somebody merged this @HassanBahati

**Comment by basiima** [comment]
Oh I guess I have to make the change

**Comment by basiima** [comment]
Alright, have fixed it. New PR in a few

**Pull request merged**
