### PR TITLE
add pycon merhandise url

### PR DESCRIPTION
**Pull request by HassanBahati**

### CODE REVIEW

**Review by Amanya-Brian — COMMENTED** [review]
Some issues are causing the deploy preview to fail. Kindly review @HassanBahati

**Comment by HassanBahati** [comment]
> Some issues are causing the deploy preview to fail. Kindly review @HassanBahati

@Amanya-Brian this should now be resolved :+1:

**Comment by Amanya-Brian** [comment]
It is, thanks.

**Review by Amanya-Brian — APPROVED** [review]
Good to go

**Pull request merged**
