### PR TITLE
change website font to Raleway

### PR DESCRIPTION
**Pull request by basiima**
Raleway is the font used throughout our documents

### CODE REVIEW

**Comment by basiima** [comment]
I have always wanted to make this change, so please accept it

**Comment by HassanBahati** [comment]
Is this what is being used in other branding too? Is it the font being considered as the official font?

**Comment by basiima** [comment]
we dont have an official font, @Amanya-Brian probably uses a different font in the designs

**Comment by basiima** [comment]
this is just for uniformity. Brian could as well change the website font to that which he uses in the designs.

**Comment by HassanBahati** [comment]
@Amanya-Brian what do you think ?

**Comment by Amanya-Brian** [comment]
image


That is the font I have been using in designs - Flux Regular

**Comment by basiima** [comment]
well I leave it to you guys

**Comment by Amanya-Brian** [comment]
@HassanBahati  the official font is Raleway. I was corrected by Fanny

**Review by Amanya-Brian — APPROVED** [review]
I think we are good to go

**Pull request merged**
