### PR TITLE
Update schedule page layout and styling

### PR DESCRIPTION
**Pull request by amkayondo**
- improve the page outline and make it responsive on mobile

### CODE REVIEW

**Comment by amkayondo** [comment]
any update on this

**Review by HassanBahati — COMMENTED** [review]
Amazing work :clap:, there seem to be some inconsistencies with time, for example one of the considerations in the current is things that cut across would appear inline. 

[in the update](https://deploy-preview-172--pyconug.netlify.app/2024/schedule), for instance lunch here appears to be 
image

[currently its looking like](https://ug.pycon.org/2024/schedule)
image

the change on that this was due to feedback that when something was happening in more than one room at the same time and wasn't appearing inline, that was causing confusion to attendees, 

the inspiration around this was to block time all through the rooms if its happening in more than one room as[ seen here ](https://us.pycon.org/2024/schedule/)
  
image

**Comment by HassanBahati** [comment]
could it be possible to keep these inline since they apply to all rooms
- lunch 
- breakfast
- breaktea
- and any other that seems to cut across

**Review by HassanBahati — APPROVED** [review]
LGTM! thanks @amkayondo :clap:

**Pull request merged**
