### PR TITLE
Close PyLadies and Django Girls registrations for PyCon Uganda 2024

### PR DESCRIPTION
**Pull request by HassanBahati**
This PR closec pyladies and django girls registrations for PyCon Uganda 2024

### CODE REVIEW

**Comment by Leon12-aaryson** [comment]
was everyone who applied accepted coz if not maybe the message should change. If everyone that applied was accepted then I believe you can merge
image

**Review by Leon12-aaryson — APPROVED** [review]
looks good.

**Comment by HassanBahati** [comment]
> was everyone who applied accepted coz if not maybe the message should change. If everyone that applied was accepted then I believe you can merge image

makes sense since not everyone might have been selected. let me adjust the wording. thanks!

**Comment by Leon12-aaryson** [comment]
> > was everyone who applied accepted coz if not maybe the message should change. If everyone that applied was accepted then I believe you can merge image
> 
> makes sense since not everyone might have been selected. let me adjust the wording. thanks!

That's fine, ggo ahead and do that

**Pull request merged**
