### PR TITLE
feat: modify schedule

### PR DESCRIPTION
**Pull request by HassanBahati**
This pr attempts to modify the schedule to be more dynamic to cater more and aggregated sessions....where some sessions will have less time than others

[last year's schedule](https://ug.pycon.org/2023/schedule)
[current schedule](https://ug.pycon.org/2024/schedule)
[schedule modification in this pr](https://deploy-preview-164--pyconug.netlify.app/2024/schedule)

### CODE REVIEW

**Comment by Leon12-aaryson** [comment]
@HassanBahati there is no description so I may not know what exactly I need to be looking at given the changes that would be required

**Comment by HassanBahati** [comment]
> @HassanBahati there is no description so I may not know what exactly I need to be looking at given the changes that were made or were required

my bad had forgotten that..just added it.

**Review by Leon12-aaryson — APPROVED** [review]
Looking at the design templates::
- the UI is much better
- Halls are visible to every reader and well organised
generally looks good

**Comment by Leon12-aaryson** [comment]
@HassanBahati you can go ahead and merge, the new design looks good

**Comment by Leon12-aaryson** [comment]
image
I was thinking you could set a maximum width to the images and or a fixed size to let them have the same size when displaying

**Comment by HassanBahati** [comment]
That issue should have been fixed via
https://github.com/PyconUg/ug.pycon.org/pull/166 please refresh your page
to see the update

**Comment by Leon12-aaryson** [comment]
Yeah I saw it, looks great

**Comment by HassanBahati** [comment]
Amazing

**Pull request merged**
